name       : xfsdump
version    : 3.1.12
release    : 5
source     :
    - https://mirrors.edge.kernel.org/pub/linux/utils/fs/xfs/xfsdump/xfsdump-3.1.12.tar.xz : f39c4c1b306b2dd7ec979c0e94d60fe69083d2ecf9af051cac5ef3bed772c74a
license    : GPL-2.0-or-later
component  : system.utils
homepage   : https://xfs.wiki.kernel.org/
summary    : xfsdump backs up files and their attributes in a filesystem. The files are dumped to storage media, a regular file, or standard output.
description: |
    xfsdump backs up files and their attributes in a filesystem. The files are dumped to storage media, a regular file, or standard output. Options allow the operator to have all files dumped, just files that have changed since a previous dump, or just files contained in a list of pathnames. The xfsrestore utility re-populates a filesystem with the contents of the dump.
builddeps  :
    - pkgconfig(libattr)
    - xfsprogs-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc

    # Move the files from /sbin/ to /usr/sbin, erasing the symlinks to /sbin in the process
    mv -vf $installdir/sbin/* $installdir/usr/sbin/
    rmdir $installdir/sbin
