name       : xfsdump
version    : 3.1.9
release    : 3
source     :
    - https://mirrors.edge.kernel.org/pub/linux/utils/fs/xfs/xfsdump/xfsdump-3.1.9.tar.xz : 55aeede6232ddce6c9e79e2af88d6f808534df1552eb2bfaf7fb85b92add6dd1
license    : GPL-2.0-or-later
component  : system.utils
homepage   : https://xfs.wiki.kernel.org/
summary    : xfsdump backs up files and their attributes in a filesystem. The files
    are dumped to storage media, a regular file, or standard output.
description: |
    xfsdump backs up files and their attributes in a filesystem. The files are dumped to storage media, a regular file, or standard output. Options allow the operator to have all files dumped, just files that have changed since a previous dump, or just files contained in a list of pathnames. The xfsrestore utility re-populates a filesystem with the contents of the dump.
builddeps  :
    - pkgconfig(libattr)
    - xfsprogs-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
